### User sign up 
POST http://localhost:3001/v1/user
Content-Type: application/json


{
    "name":"singh",
    "company":"abc",
    "address":"xxxx",
    "phone":"1234",
    "email":"a4@a.com",
    "password":"password"
}

### User sign in 
POST http://localhost:3001/v1/user/login
Content-Type: application/json


{
    "email":"a4@a.com",
    "password":"password3"
}

###verify token
GET http://localhost:3001/v1/user/login
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzU0NzQyLCJleHAiOjE2MzYzNTU2NDJ9.59GvGdLbeZ0sCBcmghjY501MabHxSk0dJTRLdINP1Ns


###verify refresh token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM1OTExNzAxLCJleHAiOjE2Mzg1MDM3MDF9.PDv3GE9XyAFRQtqZIsD_cN9JLKplOZQP-q_8IOnsTR0


###request pin
POST http://localhost:3001/v1/user/reset
Content-Type: application/json

{
    "email":"a4@a.com"
}


###reset password
PATCH  http://localhost:3001/v1/user/reset
Content-Type: application/json

{
    "email":"a4@a.com",
    "pin":"62424",
    "password":"password3"
}

###verify refresh token
DELETE  http://localhost:3001/v1/user/logout
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYyMDQ0LCJleHAiOjE2MzYzNjI5NDR9.ebOtd3Kbmp_rN2evKG3uLbBtF2qT2bG_IxNDk0QiBjE

### Post ticket
POST http://localhost:3001/v1/ticket/
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYyMDQ0LCJleHAiOjE2MzYzNjI5NDR9.ebOtd3Kbmp_rN2evKG3uLbBtF2qT2bG_IxNDk0QiBjE

{
    "subject":"login issue",
    "sender":"singh",
    "message":"I am fine"
}

### Get all ticket
GET  http://localhost:3001/v1/ticket/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYzMTM5LCJleHAiOjE2MzY0NDk1Mzl9.QcHcSy1xpLVGQB2fLocwrG1snIu41CFAQq-MNoj-la8

### Get one ticket
GET  http://localhost:3001/v1/ticket/6188e869e5fa9caf402f702e
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYzMTM5LCJleHAiOjE2MzY0NDk1Mzl9.QcHcSy1xpLVGQB2fLocwrG1snIu41CFAQq-MNoj-la8

### Reply message
PUT http://localhost:3001/v1/ticket/6188e869e5fa9caf402f702e
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYzMTM5LCJleHAiOjE2MzY0NDk1Mzl9.QcHcSy1xpLVGQB2fLocwrG1snIu41CFAQq-MNoj-la8

{
    "message":"wednesday?",
    "sender":"singh"
}

### Close ticket
PATCH  http://localhost:3001/v1/ticket/6188e869e5fa9caf402f702e
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM2MzYzMTM5LCJleHAiOjE2MzY0NDk1Mzl9.QcHcSy1xpLVGQB2fLocwrG1snIu41CFAQq-MNoj-la8

