### User sign up 
POST http://localhost:3001/v1/user
Content-Type: application/json


{
    "name":"singh",
    "company":"abc",
    "address":"xxxx",
    "phone":"1234",
    "email":"a4@a.com",
    "password":"password"
}

### User sign in 
POST http://localhost:3001/v1/user/login
Content-Type: application/json


{
    "email":"a4@a.com",
    "password":"password"
}

###verify token
GET http://localhost:3001/v1/user/login
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM1OTAzODcwLCJleHAiOjE2MzU5MDQ3NzB9.8y0tQWI_eF1C-qnG5xmQ66NstRl4X0hwPDltpg7s8BY


###verify refresh token
GET http://localhost:3001/v1/tokens
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJlbWFpbCI6ImE0QGEuY29tIiwiaWF0IjoxNjM1OTExNzAxLCJleHAiOjE2Mzg1MDM3MDF9.PDv3GE9XyAFRQtqZIsD_cN9JLKplOZQP-q_8IOnsTR0


###request pin
POST http://localhost:3001/v1/user/reset
Content-Type: application/json

{
    "email":"a4@a.com"
}


###reset password
PATCH  http://localhost:3001/v1/user/reset
Content-Type: application/json

{
    "email":"a4@a.com",
    "pin":"422286",
    "password":"password1"
}
