### User sign up 
POST http://localhost:3001/v1/user
Content-Type: application/json


{
    "name":"singh",
    "company":"abc",
    "address":"xxxx",
    "phone":"1234",
    "email":"a4@a.com",
    "password":"password"
}

### User sign in 
POST http://localhost:3001/v1/user/login
Content-Type: application/json


{
    "email":"a4@a.com",
    "password":"password"
}

###verify token
GET http://localhost:3001/v1/user/login
Authorization:yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTgxZDVkMjk4MDk0ZWU5MWMzMDZhMDAiLCJpYXQiOjE2MzU5MDM1MzUsImV4cCI6MTYzNTkwNDQzNX0.vjUpY6AtrNDK4UbtiVBui0sf0tImRYFsjfa11pH1I7k



